version: 2
updates:

  # Maintain dependencies for docker
  - package-ecosystem: "docker"
    directory: "/.github/dependabot_docker_proxy"
    schedule:
      interval: "weekly"
    
  # Maintain dependencies for pip
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
  

